#!/bin/bash
# generate-context.sh — Master context generation script
# Generates context artifacts in .claude/context/ for Claude Code sessions.
#
# Usage:
#   ./scripts/generate-context.sh          # Generate all context files
#   ./scripts/generate-context.sh ir-types  # Generate only IR types summary
#   ./scripts/generate-context.sh recent    # Generate only recent changes
#   ./scripts/generate-context.sh status    # Generate only project status
#   ./scripts/generate-context.sh arch      # Generate only architecture diagrams
#   ./scripts/generate-context.sh index     # Generate source index + call graph (requires tree-sitter)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONTEXT_DIR="$PROJECT_DIR/.claude/context"

mkdir -p "$CONTEXT_DIR"

# ============================================================================
# IR Types Summary
# ============================================================================
generate_ir_types() {
  local OUT="$CONTEXT_DIR/ir-types-summary.md"
  local SRC="$PROJECT_DIR/src/interfaces.rs"

  if [ ! -f "$SRC" ]; then
    echo "WARNING: $SRC not found, skipping IR types generation" >&2
    return
  fi

  cat > "$OUT" <<'HEADER'
# NeuroScript IR Types Summary
<!-- Auto-generated by scripts/generate-context.sh — do not edit -->

Core data types from `src/interfaces.rs`. Read this file for quick reference
instead of opening the full source.

HEADER

  # Extract public enums with their variants
  awk '
    /^pub enum / {
      enum_name = $0
      sub(/^pub enum /, "", enum_name)
      sub(/ \{.*/, "", enum_name)
      print "## enum " enum_name
      in_enum = 1
      next
    }
    /^pub\(crate\) enum / {
      enum_name = $0
      sub(/^pub\(crate\) enum /, "", enum_name)
      sub(/ \{.*/, "", enum_name)
      print "## enum " enum_name " (crate)"
      in_enum = 1
      next
    }
    in_enum && /^\}/ {
      print ""
      in_enum = 0
      next
    }
    in_enum && /^    [A-Z]/ {
      variant = $0
      # Clean up: remove leading whitespace, trailing content after variant name
      gsub(/^    /, "", variant)
      # Keep variant name and any tuple/struct hint but simplify
      if (variant ~ /\{/) {
        sub(/ \{.*/, " { ... }", variant)
      } else if (variant ~ /\(/) {
        # Keep the type hint for simple tuples
        sub(/,$/, "", variant)
      } else {
        sub(/,$/, "", variant)
      }
      print "- " variant
    }
  ' "$SRC" >> "$OUT"

  # Extract public structs with their fields
  awk '
    /^pub struct / {
      struct_name = $0
      sub(/^pub struct /, "", struct_name)
      sub(/ \{.*/, "", struct_name)
      sub(/<.*/, "", struct_name)
      # Skip if it is a unit struct or tuple struct on one line
      if ($0 ~ /;$/) {
        next
      }
      print "## struct " struct_name
      in_struct = 1
      next
    }
    in_struct && /^\}/ {
      print ""
      in_struct = 0
      next
    }
    in_struct && /pub / {
      field = $0
      gsub(/^    /, "", field)
      # Remove doc comments
      if (field ~ /^\/\/\//) next
      sub(/,$/, "", field)
      print "- " field
    }
  ' "$SRC" >> "$OUT"

  # Extract type aliases
  {
    echo "## Type Aliases"
    grep -E '^pub(\(crate\))? type ' "$SRC" | while read -r line; do
      echo "- ${line}"
    done
    echo ""
  } >> "$OUT"

  # Add key impl method signatures
  {
    echo "## Key Methods"
    echo ""
    echo "### Dim"
    grep -A1 'pub fn ' "$SRC" | grep -E '^\s+pub fn' | head -5 | while read -r line; do
      clean=$(echo "$line" | sed 's/^[[:space:]]*//' | sed 's/ {$//')
      echo "- \`$clean\`"
    done
    echo ""
  } >> "$OUT"

  echo "Generated: $OUT" >&2
}

# ============================================================================
# Recent Changes
# ============================================================================
generate_recent_changes() {
  local OUT="$CONTEXT_DIR/recent-changes.md"

  cd "$PROJECT_DIR"

  cat > "$OUT" <<HEADER
# Recent Changes
<!-- Auto-generated by scripts/generate-context.sh — do not edit -->
Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

HEADER

  {
    # Current branch
    BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")
    echo "## Branch: $BRANCH"
    echo ""

    # Uncommitted changes
    CHANGES=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    if [ "$CHANGES" -gt 0 ]; then
      echo "## Uncommitted Changes ($CHANGES files)"
      git status --porcelain 2>/dev/null | head -20
      echo ""
    fi

    # Last 10 commits with file counts
    echo "## Last 10 Commits"
    echo '```'
    git log --oneline --stat --no-merges -10 2>/dev/null | \
      awk '
        /^[0-9a-f]+ / { if (NR > 1) print ""; print $0 }
        /files? changed/ { print "  " $0 }
      '
    echo '```'
    echo ""

    # Files modified in last 3 commits with diff stats
    echo "## Files in Last 3 Commits"
    echo '```'
    git diff --stat HEAD~3..HEAD 2>/dev/null || git diff --stat $(git rev-list --max-parents=0 HEAD)..HEAD 2>/dev/null
    echo '```'
  } >> "$OUT"

  echo "Generated: $OUT" >&2
}

# ============================================================================
# Project Status
# ============================================================================
generate_project_status() {
  local OUT="$CONTEXT_DIR/project-status.md"

  cd "$PROJECT_DIR"

  cat > "$OUT" <<HEADER
# Project Status
<!-- Auto-generated by scripts/generate-context.sh — do not edit -->
Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

HEADER

  {
    echo "## Current Phase"
    echo "Phase 3: Advanced Features (Codegen complete, working on advanced language features)"
    echo ""

    # Active work from git
    BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")
    echo "## Active Work"
    echo "- Branch: $BRANCH"
    LAST_MSG=$(git log --oneline -1 2>/dev/null)
    echo "- Last commit: $LAST_MSG"
    echo ""

    # Language gaps from notes
    if [ -f "$PROJECT_DIR/notes/language-gaps.md" ]; then
      echo "## Language Gaps"
      # Extract gap headings with their status
      awk '
        /^## [0-9]+\./ {
          title = $0
          sub(/^## [0-9]+\. /, "", title)
          # Check for RESOLVED marker
          if (title ~ /RESOLVED/) {
            gsub(/~~/, "", title)
            gsub(/ *\(RESOLVED\)/, "", title)
            print "- [x] " title " (RESOLVED)"
          } else {
            gsub(/~~/, "", title)
            print "- [ ] " title
          }
        }
      ' "$PROJECT_DIR/notes/language-gaps.md"
      echo ""
    fi

    # Stdlib neuron count
    echo "## Stdlib Coverage"
    if [ -d "$PROJECT_DIR/stdlib" ]; then
      NS_COUNT=$(find "$PROJECT_DIR/stdlib" -name '*.ns' | wc -l | tr -d ' ')
      # Count neuron definitions in stdlib
      NEURON_COUNT=$(grep -r '^neuron ' "$PROJECT_DIR/stdlib/" 2>/dev/null | wc -l | tr -d ' ')
      echo "- $NS_COUNT stdlib files, $NEURON_COUNT neuron definitions"
    fi
    EXAMPLE_COUNT=$(find "$PROJECT_DIR/examples" -name '*.ns' 2>/dev/null | wc -l | tr -d ' ')
    echo "- $EXAMPLE_COUNT example files"
    echo ""

    # Generation progress if available
    if [ -f "$PROJECT_DIR/generation_progress.md" ]; then
      echo "## Generation Progress"
      # Extract summary stats
      COMPLETED=$(grep -c '^\| .* \| .*completed' "$PROJECT_DIR/generation_progress.md" 2>/dev/null || echo "0")
      PENDING=$(grep -c '^\| .* \| .*pending\|^\| .* \| .*failed' "$PROJECT_DIR/generation_progress.md" 2>/dev/null || echo "0")
      echo "- Completed: $COMPLETED"
      echo "- Pending/Failed: $PENDING"
      echo ""
    fi

    # Recent decisions from PROGRESS.md (last entry)
    if [ -f "$PROJECT_DIR/docs/PROGRESS.md" ]; then
      echo "## Recent Progress Notes"
      # Get the last session header and a few lines after it
      awk '
        /^## Session/ { found = 1; count = 0; header = $0 }
        found && count < 15 { print; count++ }
        found && count >= 15 { exit }
      ' "$PROJECT_DIR/docs/PROGRESS.md" | tail -15
      echo ""
    fi
  } >> "$OUT"

  echo "Generated: $OUT" >&2
}

# ============================================================================
# Architecture Diagrams
# ============================================================================
generate_architecture() {
  local OUT="$CONTEXT_DIR/architecture.md"

  cd "$PROJECT_DIR"

  cat > "$OUT" <<'HEADER'
# Architecture Diagrams
<!-- Auto-generated by scripts/generate-context.sh — do not edit -->

## Compilation Pipeline

```mermaid
graph LR
  Source[".ns Source"] --> Grammar["Grammar<br/>(pest PEG)"]
  Grammar --> AST["AST Builder"]
  AST --> IR["IR Types"]
  IR --> Validator
  Validator --> Optimizer
  Optimizer --> Codegen
  Codegen --> PyTorch["PyTorch<br/>nn.Module"]
  Validator --> ShapeInf["Shape<br/>Inference"]
  Validator --> Stdlib["Stdlib<br/>Registry"]
```

## Core Type Hierarchy

```mermaid
classDiagram
  Program --> UseStmt
  Program --> GlobalBinding
  Program --> NeuronDef
  NeuronDef --> Param
  NeuronDef --> Port
  NeuronDef --> NeuronBody
  NeuronDef --> Documentation
  NeuronBody --> ImplRef : Primitive
  NeuronBody --> Connection : Graph
  NeuronBody --> Binding : Graph
  Connection --> Endpoint : source
  Connection --> Endpoint : destination
  Endpoint --> PortRef : Ref
  Endpoint --> PortRef : Tuple
  Endpoint --> MatchExpr : Match
  Endpoint --> IfExpr : If
  MatchExpr --> MatchArm
  MatchArm --> Shape : pattern
  MatchArm --> Value : guard
  IfExpr --> IfBranch
  Port --> Shape
  Shape --> Dim
  Dim --> DimExpr : Expr
```

HEADER

  # Generate module dependency graph from use crate:: statements
  {
    echo "## Module Dependencies"
    echo ""
    echo '```mermaid'
    echo "graph TD"

    # Map file paths to short module names
    # Parse use crate:: imports to find edges
    find "$PROJECT_DIR/src" -name '*.rs' -not -path '*/tests/*' | sort | while read -r file; do
      rel=$(echo "$file" | sed "s|$PROJECT_DIR/src/||")
      # Derive module name from path
      mod=$(echo "$rel" | sed 's|/mod\.rs||; s|\.rs$||; s|/|_|g')

      # Find crate-internal imports
      grep -oE 'use crate::[a-z_]+' "$file" 2>/dev/null | sort -u | while read -r imp; do
        target=$(echo "$imp" | sed 's/use crate:://')
        # Skip self-references
        if [ "$target" != "$mod" ]; then
          echo "  ${mod} --> ${target}"
        fi
      done || true
    done | sort -u

    echo '```'
    echo ""
  } >> "$OUT"

  echo "Generated: $OUT" >&2
}

# ============================================================================
# Source Index + Call Graph (delegates to Python tree-sitter script)
# ============================================================================
generate_index() {
  local INDEX_SCRIPT="$SCRIPT_DIR/generate-index.py"

  if [ ! -f "$INDEX_SCRIPT" ]; then
    echo "ERROR: $INDEX_SCRIPT not found. Create it first (Phase 2)." >&2
    return 1
  fi

  # Try to use the project venv
  if [ -f "$HOME/.venv_ai/bin/activate" ]; then
    source "$HOME/.venv_ai/bin/activate"
  fi

  python3 "$INDEX_SCRIPT" "$PROJECT_DIR" "$CONTEXT_DIR"
}

# ============================================================================
# Main: dispatch subcommands or generate all
# ============================================================================
main() {
  local cmd="${1:-all}"

  case "$cmd" in
    ir-types)
      generate_ir_types
      ;;
    recent)
      generate_recent_changes
      ;;
    status)
      generate_project_status
      ;;
    arch)
      generate_architecture
      ;;
    index)
      generate_index
      ;;
    all)
      generate_ir_types
      generate_recent_changes
      generate_project_status
      generate_architecture
      # Index is optional — only if the Python script exists
      if [ -f "$SCRIPT_DIR/generate-index.py" ]; then
        generate_index || echo "WARNING: Index generation failed (tree-sitter may not be installed)" >&2
      fi
      ;;
    *)
      echo "Usage: $0 [ir-types|recent|status|arch|index|all]" >&2
      exit 1
      ;;
  esac
}

main "$@"
